import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "@next/font/local";
import { GeistSans } from "geist/font/sans";


const inter = Inter({ subsets: ["latin"] });

const agrandir = localFont({
  src: "../../public/fonts/Agrandir Wide Light 300.otf",
  variable: "--agrandir",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
